export const grid = { color: '#fff', size: '16' }
export const search = { color: '#fff', size: '24' }
export const enlarge = { color: '#6F8099', size: '24' }
export const shrink = { color: '#081C81', size: '24' }
export const charge = { color: '#fff', size: '16' }
export const x = { color: '#fff', size: '30' }
export const piechart = { color: '#2649F4', size: '24' }
export const apple = { size: '25' }
export const amazon = { color: '#000', size: '25' }
